In [2]:
import torch
import torch.nn as nn

In [11]:
class Model(nn.Module):
    def __init__(self , n_feat):
        super().__init__()
        self.linear = nn.Linear(n_feat , 1)
        self.sigmoid = nn.Sigmoid()
    def forward(self , data):
        out = self.linear(data)
        out = self.sigmoid(out)
        return out

In [19]:
data = torch.rand(10 , 5) # 10 rows , 5 columns

model = Model(data.shape[1])

model(data)

tensor([[0.6385],
        [0.6106],
        [0.5649],
        [0.5916],
        [0.6847],
        [0.6783],
        [0.5557],
        [0.6101],
        [0.6082],
        [0.5510]], grad_fn=<SigmoidBackward0>)

In [23]:
model.linear.weight

Parameter containing:
tensor([[ 0.3297,  0.0018, -0.3298,  0.4281, -0.1700]], requires_grad=True)

In [25]:
from torchinfo import summary
summary(model , input_size=(10 , 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [ ]:
import torch 
import torch.nn as nn

"""
class NeuralNetwork(nn.Module):
    def __init__(self , n_feat):
        super().__init__()
        self.linear1 = nn.Linear(n_feat , 3)
        self.linear2 = nn.Linear(3 , 1)
        self.relu = nn.ReLU()
        self.sigmoid = nn.Sigmoid()
    def forward(self , data):
        res = self.relu(
            self.linear1(data)
        )
        res = self.sigmoid(
            self.linear2(res)
        )
        return res
"""

class NeuralNetwork(nn.Module):
    def __init__(self , n_feat):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(n_feat , 3),
            nn.ReLU(),
            nn.Linear(3 , 1),
            nn.Sigmoid(),
        )        
    def forward(self , data):
        return self.network(data)

In [45]:
df = torch.rand(20 , 5)
neural_network = NeuralNetwork(df.shape[1])
neural_network(df)

tensor([[0.4963],
        [0.5201],
        [0.5315],
        [0.5147],
        [0.5161],
        [0.5190],
        [0.5101],
        [0.5258],
        [0.5177],
        [0.5142],
        [0.5240],
        [0.5090],
        [0.5225],
        [0.5035],
        [0.5330],
        [0.5131],
        [0.5127],
        [0.5215],
        [0.4971],
        [0.5189]], grad_fn=<SigmoidBackward0>)

In [46]:
from torchinfo import summary
summary(neural_network , input_size=(20 , 5))

Layer (type:depth-idx)                   Output Shape              Param #
NeuralNetwork                            [20, 1]                   --
├─Sequential: 1-1                        [20, 1]                   --
│    └─Linear: 2-1                       [20, 3]                   18
│    └─ReLU: 2-2                         [20, 3]                   --
│    └─Linear: 2-3                       [20, 1]                   4
│    └─Sigmoid: 2-4                      [20, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [ ]:
"""
print("Layer 1")
print(f"Weights : {neural_network.weight}")
print(f"Bias : {neural_network.linear1.bias}\n")
print("Layer 2")
print(f"Weights : {neural_network.linear2.weight}")
print(f"Bias : {neural_network.linear2.bias}\n")
"""

'print("Layer 1")\nprint(f"Weights : {neural_network.weight}")\nprint(f"Bias : {neural_network.linear1.bias}\n")\nprint("Layer 2")\nprint(f"Weights : {neural_network.linear2.weight}")\nprint(f"Bias : {neural_network.linear2.bias}\n")'

In [78]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers , Sequential

In [74]:
model = Sequential([
    layers.Dense(
        3,
        input_shape = (df.shape[1] , ),
        activation = "relu"
    ),
    layers.Dense(
        1,
        activation = "sigmoid"
    )
])
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_13 (Dense)                │ (None, 3)              │            18 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 22 (88.00 B)

 Trainable params: 22 (88.00 B)

 Non-trainable params: 0 (0.00 B)

In [83]:
model.compile(
    loss = "binary_crossentropy",
    optimizer = keras.optimizers.Adam(learning_rate = 0.01),
    metrics = ["accuracy"]
)

In [ ]:
model.fit(
    
)