In [100]:
import torch
print(torch.__version__)
if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")

2.11.0+cu128
GPU: NVIDIA GeForce RTX 4060 Laptop GPU


### Creating Tensor

In [101]:
torch.empty(3,4)

tensor([[-2.0000e+00,  1.8456e+00,  3.6893e+19,  1.8538e+00],
        [ 0.0000e+00,  1.6914e+00, -2.0000e+00,  1.8648e+00],
        [-0.0000e+00,  1.6952e+00, -3.6893e+19,  1.7752e+00]])

In [102]:
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [103]:
torch.ones(5,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [104]:
torch.rand(3,2)

tensor([[0.5315, 0.1587],
        [0.6542, 0.3278],
        [0.6532, 0.3958]])

In [105]:
torch.manual_seed(42)
torch.rand(3,2)

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593],
        [0.3904, 0.6009]])

In [106]:
torch.tensor([[1,2,3,9],[4,5,6,8],[7,8,9,0]])

tensor([[1, 2, 3, 9],
        [4, 5, 6, 8],
        [7, 8, 9, 0]])

In [107]:
print(torch.arange(1,13,2))
print(torch.linspace(0,10,20))
print(torch.eye(4))
print(torch.full((3,3),6))

tensor([ 1,  3,  5,  7,  9, 11])
tensor([ 0.0000,  0.5263,  1.0526,  1.5789,  2.1053,  2.6316,  3.1579,  3.6842,
         4.2105,  4.7368,  5.2632,  5.7895,  6.3158,  6.8421,  7.3684,  7.8947,
         8.4211,  8.9474,  9.4737, 10.0000])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
tensor([[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]])


In [108]:
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
x.shape

torch.Size([3, 3])

In [109]:
torch.empty_like(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [110]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [111]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [112]:
y = torch.tensor([[1,2,3],[4,5,6],[7,8,9]] , dtype=torch.float64)
y

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]], dtype=torch.float64)

In [113]:
torch.rand_like(y)

tensor([[0.0526, 0.5262, 0.4768],
        [0.9552, 0.9288, 0.0835],
        [0.1326, 0.1571, 0.3754]], dtype=torch.float64)

In [114]:
torch.rand_like(x , dtype=torch.float64)

tensor([[0.8425, 0.8705, 0.3775],
        [0.6124, 0.0881, 0.7012],
        [0.6234, 0.4373, 0.0747]], dtype=torch.float64)

### Matrix Multiplication

In [ ]:
a = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
b = torch.tensor([[9,8,7],[6,5,4],[3,2,1]])

torch.matmul(a,b) # Matrix Multiplication
a@b # Matrix Multiplication

tensor([[ 30,  24,  18],
        [ 84,  69,  54],
        [138, 114,  90]])

In [125]:
f=torch.randint(size=(3,4) , low=0 , high=11 , dtype=torch.float64)
f

tensor([[ 1.,  8.,  7.,  9.],
        [ 5.,  6.,  4.,  4.],
        [ 7.,  0.,  8., 10.]], dtype=torch.float64)

In [126]:
torch.transpose(f , 0,1)

tensor([[ 1.,  5.,  7.],
        [ 8.,  6.,  0.],
        [ 7.,  4.,  8.],
        [ 9.,  4., 10.]], dtype=torch.float64)

In [130]:
h = torch.tensor([[1,2,3],[4,5,6],[7,8,9]] , dtype=torch.float32)
torch.inverse(h)

tensor([[ -2796203.5000,   5592406.0000,  -2796203.5000],
        [  5592405.0000, -11184812.0000,   5592407.0000],
        [ -2796201.7500,   5592406.0000,  -2796203.5000]])